Задание 6. Добавленна функциональность регистрации пользователя
gpb-it-factory/davydova-telegram-bot pull request #8
Opened 2024-06-14 21:34 UTC by alina-gasprom

2024-06-18 07:51 UTC, konstantin-kozlovskiy requested changes
Необходимо исправить опечатки

2024-06-18 07:51 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpf/telegram/util/BotAnswer.java
> +    private static final String REGISTER_ERROR_ANSWER = "Два раза нельзя войти в одну и ту же реку и зарегестрироваться в одном и том же сервисе";
орфографические ошибки недопустимы в процессе общения с клиентом =) во всех словах "зарегистрирован" буква е вместо и

2024-06-18 14:21 UTC, alina-gasprom commented on src/main/java/ru/gpf/telegram/util/BotAnswer.java
> +    private static final String REGISTER_ERROR_ANSWER = "Два раза нельзя войти в одну и ту же реку и зарегестрироваться в одном и том же сервисе";
Побудил настроить идею под русский словарь, нашла еще опечатки)

2024-06-20 13:07 UTC, konstantin-kozlovskiy approved these changes

2024-06-20 13:40 UTC, merged